package kr.co.demo.client.mybatis.util;

import kr.co.demo.core.storage.annotation.StorageColumn;
import kr.co.demo.core.storage.annotation.StorageId;
import kr.co.demo.core.storage.annotation.StorageTable;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;

public class InsertSqlProvider {

    public static String build(Object domain) {
        Class<?> type = domain.getClass();

        String table = resolveTable(type);

        List<String> columns = new ArrayList<>();
        List<String> values = new ArrayList<>();

        for (Field field : type.getDeclaredFields()) {
            field.setAccessible(true);

            if (field.isAnnotationPresent(StorageId.class)) {
                StorageId id = field.getAnnotation(StorageId.class);
                if (id.autoGenerated()) continue;
            }

            Object value;
            try {
                value = field.get(domain);
            } catch (IllegalAccessException e) {
                continue;
            }

            if (value != null) {
                String column = resolveColumn(field);
                columns.add(column);
                values.add("#{" + field.getName() + "}");
            }
        }

        if (columns.isEmpty()) {
            throw new IllegalStateException("INSERT 대상 필드 없음");
        }

        return "INSERT INTO " + table +
                " (" + String.join(", ", columns) + ")" +
                " VALUES (" + String.join(", ", values) + ")";
    }

    /* ================= helper ================= */

    private static String resolveTable(Class<?> type) {
        StorageTable table = type.getAnnotation(StorageTable.class);
        if (table == null) {
            throw new IllegalStateException("@StorageTable 없음: " + type.getName());
        }
        return table.value();
    }

    private static String resolveColumn(Field field) {
        StorageColumn column = field.getAnnotation(StorageColumn.class);
        if (column != null && !column.value().isBlank()) {
            return column.value();
        }
        return toColumn(field.getName());
    }

    private static String toColumn(String fieldName) {
        StringBuilder sb = new StringBuilder();
        for (char c : fieldName.toCharArray()) {
            if (Character.isUpperCase(c)) {
                sb.append('_').append(Character.toLowerCase(c));
            } else {
                sb.append(c);
            }
        }
        return sb.toString();
    }
}
